# Generated by Django 4.1.2 on 2022-10-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_matches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['-date']},
        ),
    ]
